In [4]:
import numpy as np

In [5]:
print("hello world")

hello world


In [6]:
import sklearn

In [7]:
i=45

In [8]:
print(7)

7


In [9]:
i

45

In [10]:
import numpy as np  

In [11]:
myarr = np.array([1, 2, 3, 4]) #this i show you can create an array

In [12]:
myarr  #printing the array

array([1, 2, 3, 4])

In [13]:
#we'll firsrt intialize an arrat
a= np.array([9,18,27,36,45])
print(a) 

[ 9 18 27 36 45]


In [14]:
#here we are creating a two dimensional array
b=np.array([[9.0,8.0,11.0],[2.3,3.9,5.8]])
print(b)

[[ 9.   8.  11. ]
 [ 2.3  3.9  5.8]]


In [15]:
'''it tells you what's the dimention of the array. As b was two dimensional array it's gonna show 2'''
b.ndim

2

In [16]:
'''so it's give the info about the rows and columns that array so it becomes easier to visualize'''
b.shape

(2, 3)

In [17]:
#to get the size of the array you can use .dtype that basically means variable.datatype
b.dtype


dtype('float64')

In [18]:
#to get a specific element from the element array you can use the [row, column] this type of method
#so first let's declare an array. and the good thing about this is that you can also do the negative rotation
c=np.array([[2,4,5,6,7,9],[1,2,3,4,5,6]])
print(c)


[[2 4 5 6 7 9]
 [1 2 3 4 5 6]]


In [19]:
c.shape

(2, 6)

In [20]:
c[0,0]

2

In [21]:
c[1,2]

3

In [22]:
#you can also slice up the a specefic row
c[1, :]

array([1, 2, 3, 4, 5, 6])

In [23]:
#you can also slice up the a specefic columns is the complete opposite method how you got the rows
c[:, 2]

array([5, 3])

In [24]:
#getting little more fancy to speceficely target some elements [startindex:endindex:stepsize]
c[0,1:6:3]

array([4, 7])

In [25]:
#you can also targer a particular element and change its value here's example
c[1,4]=69
print(c)

[[ 2  4  5  6  7  9]
 [ 1  2  3  4 69  6]]


In [26]:
#so let's use a 3d array
three=np.array([[[2,3],[4,5],[5,7]],[[3,4],[6,8],[3,5]]])
three.shape

(2, 3, 2)

In [27]:
#you can initialize all zeros matrix
#all zeros matrix . there's a built in function for this
np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [29]:
#you can make two dimentional arrays to here's how
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros(((3,4,5)))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])